#------------------------------------------------------------------
# Bryan Crawley
# CS3233
# Normal vector demonstration
#
# This builds the demonstration of normal vectors that we will
# discuss in class. Notice that the Eck camera API must be
# present to build correctly.
#------------------------------------------------------------------

a.out: normalVectorDemo.cpp camera.cpp camera.h
	g++ normalVectorDemo.cpp camera.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
