#--------------------------------------------------------
# OpenGL Hello World
#--------------------------------------------------------

a.out: triangle.cpp
	g++ triangle.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
