#----------------------------------------------------------------
# Bryan Crawley
# Lighted Cube example
#
# This is a quick-and-easy makefile that you can use for a lot
# of testing and debugging situations. For a completed project,
# you do well to create a makefile specific to that project.
#----------------------------------------------------------------

a.out: *.cpp
	g++ *.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
