#--------------------------------------------------------
# Transforms assignment Makefile
#--------------------------------------------------------

a.out: transforms.cpp
	g++ transforms.cpp defs.cpp
clean:
	rm -f a.out
