#--------------------------------------------------------
# House drawing assignment Makefile
#--------------------------------------------------------

a.out: house.cpp
	g++ house.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
