#---------------------------------------------------------------------
# Build the cube rotation application with the trackball capability
# from Eck's camera API.
#---------------------------------------------------------------------

a.out: exampart2.cpp camera.cpp camera.h
	g++ exampart2.cpp camera.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
